"""empty message

Revision ID: 9cb442b54712
Revises: 7602ef54a468
Create Date: 2024-10-22 09:38:53.986187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb442b54712'
down_revision = '7602ef54a468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('guests', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
