"""adds image in rooms table

Revision ID: eac6bc42d8d1
Revises: d7ed01f28f94
Create Date: 2024-10-21 22:14:23.727117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac6bc42d8d1'
down_revision = 'd7ed01f28f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'image')
    # ### end Alembic commands ###
